#! /bin/sh
# DO NOT EDIT. Generated by terravalet.
# WARNING: check the order of resources before running this script.
#
# This script will "terraform state rm" 10 items.

# Uncomment this if you want to stop the script at first error
# set -e

terraform state rm \
    "module.github.github_issue_label.all_labels[\"test-import-bar.multi word label\"]"

terraform state rm \
    "module.github.github_branch_protection_v3.settings[\"test-import-bar:master\"]"

terraform state rm \
    "module.github.github_branch_default.default[\"test-import-bar\"]"

terraform state rm \
    "module.github.github_branch_protection_v3.settings[\"test-import-foo:master\"]"

terraform state rm \
    "module.github.github_branch_default.default[\"test-import-foo\"]"

terraform state rm \
    "module.github.github_branch_protection_v3.settings[\"test-import-gh:master\"]"

terraform state rm \
    "module.github.github_branch_default.default[\"test-import-gh\"]"

terraform state rm \
    "module.github.github_repository.repos[\"test-import-gh\"]"

terraform state rm \
    "module.github.github_repository.repos[\"test-import-foo\"]"

terraform state rm \
    "module.github.github_repository.repos[\"test-import-bar\"]"

