#! /bin/sh
# DO NOT EDIT. Generated by terravalet.
# WARNING: check the order of resources before running this script.
#
# This script will "terraform import" 14 items.

# Uncomment this if you want to stop the script at first error
# set -e
set -x

terraform import \
    "module.github.github_repository.repos[\"test-import-bar\"]" "test-import-bar"

terraform import \
    "module.github.github_repository.repos[\"test-import-foo\"]" "test-import-foo"

terraform import \
    "module.github.github_repository.repos[\"test-import-gh\"]" "test-import-gh"

terraform import \
    "module.github.github_branch_default.default[\"test-import-gh\"]" "test-import-gh"

terraform import \
    "module.github.github_branch_protection_v3.settings[\"test-import-gh:master\"]" "test-import-gh:master"

terraform import \
    "module.github.github_branch_default.default[\"test-import-foo\"]" "test-import-foo"

terraform import \
    "module.github.github_branch_protection_v3.settings[\"test-import-foo:master\"]" "test-import-foo:master"

terraform import \
    "module.github.github_repository_collaborator.all_collaborators[\"test-import-foo.Pix4D-Janus\"]" "test-import-foo:Pix4D-Janus"

terraform import \
    "module.github.github_team_repository.all_teams[\"test-import-foo.developers\"]" "2817139:test-import-foo"

terraform import \
    "module.github.github_branch_default.default[\"test-import-bar\"]" "test-import-bar"

terraform import \
    "module.github.github_branch_protection.settings[\"test-import-bar:master\"]" "test-import-bar:master"

terraform import \
    "module.github.github_branch_protection_v3.settings[\"test-import-bar:master\"]" "test-import-bar:master"

terraform import \
    "module.github.github_issue_label.all_labels[\"test-import-bar.multi word label\"]" "test-import-bar:multi word label"

terraform import \
    "module.github.github_repository_autolink_reference.global_autolinks[\"test-autolink-import.MYLINK-\"]" "test-autolink-import/WEBGIS-"

