package main

import (
	"strings"
	"testing"

	"github.com/go-quicktest/qt"
)

func TestGenerateRemoveScript(t *testing.T) {
	addresses := []string{
		`module.a.b.c["foo"]`,
		`module.a.b.d["foo.AN-"]`,
	}
	var bld strings.Builder
	want := `#! /bin/sh
# DO NOT EDIT. Generated by https://github.com/pix4D/terravalet
# This script will remove 2 items.

set -e

terraform state rm 'module.a.b.c["foo"]'
terraform state rm 'module.a.b.d["foo.AN-"]'

`

	generateRemoveScript(&bld, addresses)
	qt.Assert(t, qt.Equals(bld.String(), want))
}
