#! /bin/sh
# DO NOT EDIT. Generated by https://github.com/pix4D/terravalet
#
# This script will detach 6 items.

set -e

terraform state rm 'module.github.github_branch_default.default["crane-camera-ccqc"]'

terraform state rm 'module.github.github_repository.repos["crane-camera-ccqc"]'

terraform state rm 'module.github.github_repository_autolink_reference.repo_autolinks["crane-camera-ccqc.AN-"]'

terraform state rm 'module.github.github_repository_autolink_reference.repo_autolinks["crane-camera-ccqc.CV-"]'

terraform state rm 'module.github.github_repository_autolink_reference.repo_autolinks["crane-camera-ccqc.OPF-"]'

terraform state rm 'module.github.github_repository_collaborators.repo_collaborators["crane-camera-ccqc"]'
