#! /bin/sh
# DO NOT EDIT. Generated by terravalet.
# terravalet_output_format=2
#
# This script will move 1 items.

set -e

terraform state mv -lock=false -state=01-before.tfstate -state-out=dummy-01-after.tfstate \
    'null_resource.res1' \
    'null_resource.res1'

