# based on https://github.com/marco-m/timeit/blob/master/.github/workflows/ci.yml

on: [push, pull_request_target]
name: CI
jobs:
  all:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
        task-version: [v3.10.0]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install task ${{ matrix.task-version }}
      run: go install github.com/go-task/task/v3/cmd/task@${{ matrix.task-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        # By default, actions/checkout will persist the GITHUB_TOKEN, so that further
        # steps in the job can perform authenticated git commands (that is: WRITE to
        # the repo). Following the Principle of least privilege, we disable this as long
        # as we don't need it.
        persist-credentials: false
    - run: task install:deps
    - run: task lint
    - run: task test
