# based on https://github.com/marco-m/timeit/blob/master/.github/workflows/ci.yml

on: [push, pull_request_target]
name: CI
jobs:
  all:
    strategy:
      matrix:
        go-version: [1.26.x]
        os: [ubuntu-latest]
        task-version: [v3.44.1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # ratchet:actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install task ${{ matrix.task-version }}
        run: go install github.com/go-task/task/v3/cmd/task@${{ matrix.task-version }}
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
        with:
          # By default, actions/checkout will persist the GITHUB_TOKEN, so that further
          # steps in the job can perform authenticated git commands (that is: WRITE to
          # the repo). Following the Principle of least privilege, we disable this as long
          # as we don't need it.
          persist-credentials: false
      - run: task install:deps
      - run: task lint
      - run: task test
      - run: task build
