#! /usr/bin/sh
# DO NOT EDIT. Generated by terravalet.
# terravalet_output_format=1
#
# This script will move 3 items.

set -e

echo ">>> 1/3"
terraform state mv -state=local.tfstate \
    'aws_batch_compute_environment.concourse_gpu_batch' \
    'module.ci.aws_batch_compute_environment.concourse_gpu_batch'

echo ">>> 2/3"
terraform state mv -state=local.tfstate \
    'aws_instance.bar' \
    'module.ci.aws_instance.bar'

echo ">>> 3/3"
terraform state mv -state=local.tfstate \
    'aws_instance.foo["cloud"]' \
    'module.ci.aws_instance.foo["cloud"]'

