#! /usr/bin/sh
# DO NOT EDIT. Generated by terravalet.
# terravalet_output_format=2
#
# This script will move 3 items.

set -e

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.artifactory' \
    'aws_route53_record.localhostnames_public["artifactory"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.artifactory_loopback' \
    'aws_route53_record.loopback["artifactory"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.artifactory_private' \
    'aws_route53_record.private["artifactory"]'

