#! /usr/bin/sh
# DO NOT EDIT. Generated by terravalet.
# terravalet_output_format=2
#
# This script will move 3 items.

set -e

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.localhostnames_public["artifactory"]' \
    'aws_route53_record.artifactory'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.loopback["artifactory"]' \
    'aws_route53_record.artifactory_loopback'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.private["artifactory"]' \
    'aws_route53_record.artifactory_private'

