#! /bin/sh
# DO NOT EDIT. Generated by terravalet.
# terravalet_output_format=2
#
# This script will move 10 items.

set -e

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka' \
    'aws_route53_record.localhostnames_public["anka"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka-api' \
    'aws_route53_record.localhostnames_public["anka-api"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka-test' \
    'aws_route53_record.localhostnames_public["anka-test"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka_api_loopback' \
    'aws_route53_record.loopback["anka-api"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka_loopback' \
    'aws_route53_record.loopback["anka"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka_private' \
    'aws_route53_record.private["anka"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.anka_test_loopback' \
    'aws_route53_record.loopback["anka-test"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.artifactory' \
    'aws_route53_record.localhostnames_public["artifactory"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.artifactory_loopback' \
    'aws_route53_record.loopback["artifactory"]'

terraform state mv -lock=false -state=local.tfstate \
    'aws_route53_record.artifactory_private' \
    'aws_route53_record.private["artifactory"]'

