#! /usr/bin/sh
# DO NOT EDIT. Generated by terravalet.
# terravalet_output_format=2
#
# This script will move 3 items.

set -e

terraform state mv -lock=false -state=src-dummy -state-out=dst-dummy \
    'aws_batch_compute_environment.foo_batch' \
    'aws_batch_compute_environment.foo_batch'

terraform state mv -lock=false -state=src-dummy -state-out=dst-dummy \
    'aws_batch_job_definition.foo' \
    'aws_batch_job_definition.foo'

terraform state mv -lock=false -state=src-dummy -state-out=dst-dummy \
    'aws_batch_job_queue.foo' \
    'aws_batch_job_queue.foo'

