#! /bin/sh
# DO NOT EDIT. Generated by terravalet.
# WARNING: check the order of resources before to run.
#
# This script will import 9 items.

# Uncomment this if you want to stop the script at first error
# set -e

terraform import \
    'module.github.github_repository.repos["test-import-bar"]' test-import-bar

terraform import \
    'module.github.github_repository.repos["test-import-foo"]' test-import-foo

terraform import \
    'module.github.github_repository.repos["test-import-gh"]' test-import-gh

terraform import \
    'module.github.github_branch_default.default["test-import-gh"]' test-import-gh

terraform import \
    'module.github.github_branch_protection_v3.settings["test-import-gh:master"]' test-import-gh:master

terraform import \
    'module.github.github_branch_default.default["test-import-foo"]' test-import-foo

terraform import \
    'module.github.github_branch_protection_v3.settings["test-import-foo:master"]' test-import-foo:master

terraform import \
    'module.github.github_branch_default.default["test-import-bar"]' test-import-bar

terraform import \
    'module.github.github_branch_protection_v3.settings["test-import-bar:master"]' test-import-bar:master

